version: '3.7'
services:

  mysql:
    image: mysql:8
    cap_add:
      - SYS_NICE
#    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
      - ./app/docker/development/db/my.cnf:/etc/mysql/my.cnf

  app-nginx:
    build:
      context: ./app/docker/development
      dockerfile: nginx.docker
    volumes:
      - ./app:/var/www/html
    depends_on:
      - app-php-fpm
    ports:
      - "8080:80"

  app-php-fpm:
    build:
      context: ./app/docker/development
      dockerfile: php-fpm.docker
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./app:/var/www/html

  app-php-cli:
    build:
      context: ./app/docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./app:/var/www/html
      - composer:/root/.composer/cache
    links:
      - mysql
    depends_on:
      - mysql
    tty: true

  app-node-cli:
    build:
      context: ./app/docker/development
      dockerfile: node.docker
    volumes:
      - ./app:/var/www/html
#    tty: true

volumes:
  composer:
  db:
    driver: local
